### ISSUE TITLE
Move interconnection distance from landfall to export system

### ISSUE THREAD

**Issue by JakeNunemaker** [WISDEM/ORBIT#147]
I helped Becca and Sophie debug some odd numbers yesterday and realized during that this configuration is kinda hidden off on it's own. It might make sense to move into the `export_system_design` sub dict in both the new module and the old one so it's a bit more obvious that it can be modified and has a default value associated with it.

https://github.com/WISDEM/ORBIT/blob/0fadefcaa9023ab901617455b74040d9a7aee595/ORBIT/phases/design/export_system_design.py#L40
https://github.com/WISDEM/ORBIT/blob/0fadefcaa9023ab901617455b74040d9a7aee595/ORBIT/phases/design/electrical_export.py#L18

@rrolph575 @amcooperman FYI

**Comment by nRiccobo** [comment]
Fixed with #149
