### ISSUE TITLE
Library bug in HPC environment

### ISSUE THREAD

**Issue by jaredthomas68** [WISDEM/ORBIT#159]
I am using ORBIT as a dependency in GreenHEART(HOPP). When I run on Kestrel I get the following error: 

`ORBIT.core.exceptions.LibraryItemNotFoundError: XLPE_185mm_66KV.yaml not found in /kfs3/scratch/<username>/<projects>/<path>/./input/cables.`

The path given in the message should have been initialized as an ORBIT library path, but the file specified should be coming from the standard ORBIT library. I tried putting the ORBIT standard library at the path given and still got the same error.

This is not just a general MPI issue as I am able to run the exact same scripts in parallel on my local machine just fine.

I also got the same error using both the current state of the semi-taught mooring branch and an older state (3baed36052d7503de6ea6f2db0b40945d637ea35).

My guess is that this has to do with communication and proper inclusion of package data for package installation in the `setup.py`. 

I get the same error running on a single node or across multiple nodes.

**Comment by jaredthomas68** [comment]
Thanks, I'll try that and let you know 

> You are likely on the right track. When you use ORBIT as a dependency are you installing the source code or just using `pip install orbit-nrel` in your setup.py?

I was using `pip install` in a `requirements.txt` file, but have also tried installing from source. I get the same error both ways.

**Comment by jaredthomas68** [comment]
> Hi @jaredthomas68, this might have to do with where the default library is installed vs where it's expected, and based on a quick chat with Nick, this is roughly in line with what you were seeing when digging deeper.
> 
> What I'd recommend is to clone ORBIT to a preferred location (home or project folder), and then reference the library contained there instead of relying on the ORBIT default library. In an entirely unrelated project, we do something similar so that the references stay fixed.

I have tried  putting the full ORBIT library in my project directory, but that did not work. I can try pointing my project to the cloned ORBIT repo directory. Thank you for the suggestion. I'll let you know if that works.

**Comment by RHammond2** [comment]
Without telling ORBIT to use that directory as the library, then it'll be using the default library, so be sure when running ORBIT that the library is specifically being set.

**Comment by jaredthomas68** [comment]
Ok, I specifically set the library to ORBIT's installed library and that worked except that I need both default library files and a few unique files in a local library I was setting. The next step would have been to copy my files into the ORBIT library I was pointing to, but then I got looking at the paths more closely again. It turns out my real problem was case. My orbit input file specified the cable type with a capital "K" in "KV", but the file I need uses a lower case "k" in "kV". I had carefully checked the path previously, but somehow missed the error in the file name itself. I'm not sure why the upper case version worked on my local system, but it did.

Thank you for your help. I apologize for much ado about nothing. I am glad to know about these other solution approaches though, I may need them down the road.

**Comment by RHammond2** [comment]
Either way I'm glad you were able to get it all sorted, and get some additional usage know-how!
