### ISSUE TITLE
Non-unique plant capacity in export cable sizing

### ISSUE THREAD

**Issue by Matt-Shields** [WISDEM/ORBIT#32]
https://github.com/WISDEM/ORBIT/blob/182d810b3372d4dbf70c205aa2988775b3c10de5/ORBIT/phases/design/export_system_design.py#L80

If I specify plant capacity and turbine rating, this overrides the input value of plant capacity and can lead to an extra export cable being created from rounding error stackup.  

Example: 600MW plant with 18 MW turbines.  Project manager rounds up to 34 turbines; export_system then sizes export cables for 34 x 18 = 612 MW plant.  A 220 kV export cable has a rating of 304 MW, so this erroneously adds a third export cable.

**Comment by JakeNunemaker** [comment]
Do you want the input capacity value to be used for the export system design even if the rest of the model needs an integer number of turbines and will need to either round up/down?

**Comment by Matt-Shields** [comment]
yeah, i think that works. ideally the user should input a consistent number of turbines/plant capacty, but that doesn't work for some of our parameter sweeps.  something we should just keep in mind for single-plant studies.
