### ISSUE TITLE
Library data not insalling via conda

### ISSUE THREAD

**Issue by RHammond2** [WISDEM/ORBIT#40]
There is a potential issue of the `library` folder not installing when installing `WISDEM` via `conda`.

Someone reached out to me about an issue with the `default_library` not existing when using a freshly installed version of `ORBIT`. I don't have any information on the system they're using just that they used a `conda` installation of `WISDEM`.

Update: Installing via source does not produce this same issue, only a `conda` installation is leaving out the `library` folder.

**Comment by gbarter** [comment]
This might be more of a WISDEM issue.  I'll have to look into it.

**Comment by RHammond2** [comment]
From [here](https://stackoverflow.com/a/26533921) it seems like it needs to be registered as package data so that it also gets installed, so some edits would need to be made to the `ORBIT` setup.py file.

**Comment by RHammond2** [comment]
A few more [details](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files).

**Comment by gbarter** [comment]
I've replicated the problem.  Yes, we just need `__init__.py` files in the library directory tree.

**Comment by gbarter** [comment]
I have fixed this in the WISDEM copy of ORBIT.  I will leave it to the ORBIT dev team to address it here, unless you would like me to submit a PR.

**Comment by RHammond2** [comment]
@JakeNunemaker do you have any preference on this matter?

**Comment by JakeNunemaker** [comment]
I just saw this - the emails must have slipped through the cracks in my gmail.

No preference here. Just adding an __init__ to the library works? I can add that if so.

**Comment by gbarter** [comment]
Yup, you got it.
