### ISSUE TITLE
Make ORBIT pip installable

### ISSUE THREAD

**Issue by JakeNunemaker** [WISDEM/ORBIT#64]

**Comment by JakeNunemaker** [comment]
Closed with v0.5.2 release

**Comment by skannerdarkly** [comment]
This works great, but I believe you broke some of the examples when this happened. Specifically around the import of library.

**Comment by JakeNunemaker** [comment]
@skannerdarkly What version are you working with? And how are you trying to use the library? It has worked on my end since adding this issue was closed
